#pragma once

#define EFFEKSEER_MAX_PARTICLE 10000
#define EFFEKSEER_EFFECT_MAX 32

enum EffekseerEffectType
{
	EFFEKSEER_HIT,
	EFFEKSEER_PLAYER_DEAD,
	EFFEKSEER_BOSSDEAD,
	EFFEKSEER_EFFECT_TYPE_MAX
};
